steps:
  # Step 1 : Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/submission-mgce-dhillen/recommendation', '.']

  # Step 2 : Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/submission-mgce-dhillen/recommendation']

  # Step 3 : Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'recommendation'
      - '--image'
      - 'asia.gcr.io/submission-mgce-dhillen/recommendation'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
